// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANygUfmr4Cgg3RdgKI-JJZCimAmaSkYKc',
    appId: '1:578308746609:android:6bf8ef224c25ab4159dad0',
    messagingSenderId: '578308746609',
    projectId: 'my-notes-3f485',
    storageBucket: 'my-notes-3f485.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCogwywVsbO4kkC0OJnNIyathcPmlP7NFA',
    appId: '1:578308746609:ios:6c2efa75a8e5638759dad0',
    messagingSenderId: '578308746609',
    projectId: 'my-notes-3f485',
    storageBucket: 'my-notes-3f485.appspot.com',
    iosClientId: '578308746609-u3jn44hjtvv3j8ttn973tn5q5056aecb.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotesss',
  );
}
